name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t gurpreetkaur94/practice/multi-container-react -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true gurpreetkaur94/practice/multi-container-react npm test
      - run: docker build -t gurpreetkaur94/multi-container-react-client ./client
      - run: docker build -t gurpreetkaur94/multi-container-react-server ./server
      - run: docker build -t gurpreetkaur94/multi-container-react-nginx ./nginx
      - run: docker build -t gurpreetkaur94/multi-container-react-worker ./worker
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push gurpreetkaur94/multi-container-react-client
      - run: docker push gurpreetkaur94/multi-container-react-server
      - run: docker push gurpreetkaur94/multi-container-react-nginx
      - run: docker push gurpreetkaur94/multi-container-react-worker     
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-client-docker
          environment_name: Multiclientdocker-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-1-837170667903
          region: ap-northeast-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
